# Generated by Django 2.2.3 on 2020-08-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0008_auto_20190720_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commendation',
            name='created',
            field=models.DateField(blank=True, db_index=True, verbose_name='дата'),
        ),
    ]
